server.port=${PORT:8080}

# H2 baza
spring.datasource.url=jdbc:h2:file:./data/usluznosecenje
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# Mail - vrednosti dolaze iz environment varijabli
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.username=masterso2004@gmail.com
spring.mail.password=xgjc mruh wfyc zjpi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=3000
spring.mail.properties.mail.smtp.timeout=3000

# Multipart upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=26MB

# App
app.mail.admin=masterso2004@gmail.com